package edu.mis.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("commodity", "id", Commodity.class);
		arp.addMapping("commoditytype", "id", Commoditytype.class);
		arp.addMapping("customer", "id", Customer.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("user", "id", User.class);
	}
}

