package edu.mis.model;

import java.util.List;

import edu.mis.model.base.BaseCommoditytype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commoditytype extends BaseCommoditytype<Commoditytype> {
	public static final Commoditytype dao = new Commoditytype().dao();
	/**
	 * 查询所有用户
	 * @return
	 */
	public List<Commoditytype> findAll(){
		return dao.find("SELECT * FROM Commoditytype");
	}
	/**
	 * 根据用户名查找用户
	 * @param name
	 * @return
	 */
	public Commoditytype findCommoditytypeByName(String name){
		return findFirst("SELECT * FROM Commoditytype WHERE name = ? ",name);
	}
	public List<Commodity> getCommoditys(){
		return Commodity.dao.find("SELECT *  FROM Commodity WHERE type=?",get("id"));
	}
}
