package edu.mis.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import edu.mis.model.base.BaseCommodity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commodity extends BaseCommodity<Commodity> {
	public static final Commodity dao = new Commodity().dao();
	/**
	 * 关联查询_查询所有用户及其权限(权限:用户为1对多)
	 * @return
	 */
	public List<Record> findAllRecord(){
		return Db.find("SELECT c.*,t.name FROM commodity c LEFT JOIN commoditytype t ON c.type=t.id" );
	}
	
	/**
	 * 查询所有用户
	 * @return
	 */
	public List<Commodity> findAll(){
		return dao.find("SELECT * FROM Commodity");
	}
	/**
	 * 根据用户名查找用户
	 * @param name
	 * @return
	 */
	public Commodity findCommodityByName(String name){
		return findFirst("SELECT * FROM Commodity WHERE commodityName = ? ",name);
	}
	
	/**
	 * 表关联查询_得到用户的角色
	 * 权限:用户为1:N关系，得到用户对象的角色。
	 * @return
	 */
	public Commoditytype getCommoditytype(){
		return Commoditytype.dao.findById(get("type"));
	}
}
