package edu.mis.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import edu.mis.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer().dao();	
	/**
	 * 查询所有用户
	 * @return
	 */
	public List<Customer> findAll(){
		return dao.find("SELECT * FROM customer");
	}
	/**
	 * 根据用户名查找用户
	 * @param name
	 * @return
	 */
	public Customer findCustomerByName(String name){
		return findFirst("SELECT * FROM customer WHERE name = ? ",name);
	}
	
}
