package edu.mis.model;

import java.util.List;

import edu.mis.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();
	/**
	 * 查询所有权限
	 * @return
	 */
	public List<Role> findAll(){
		return dao.find("SELECT * FROM role");
	}
	
	/**
	 * 表关联查询_得到拥有该权限的所有用户
	 * 权限:用户为1:N关系，根据1找到所有N
	 * 参考JFINAL官方手册
	 * @return
	 */
	public List<User> getUsers(){
		return User.dao.find("SELECT *  FROM user WHERE roleId=?",get("id"));
	}
}
