package edu.mis.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import edu.mis.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	/**
	 * 关联查询_查询所有用户及其权限(权限:用户为1对多)
	 * @return
	 */
	public List<Record> findAllRecord(){
		return Db.find("SELECT u.*,r.roleName FROM user u LEFT JOIN role r ON u.roleId=r.id" );
	}
	
	/**
	 * 查询所有用户
	 * @return
	 */
	public List<User> findAll(){
		return dao.find("SELECT * FROM user");
	}
	/**
	 * 根据用户名查找用户
	 * @param name
	 * @return
	 */
	public User findUserByName(String name){
		return findFirst("SELECT * FROM user WHERE name = ? ",name);
	}
	
	/**
	 * 表关联查询_得到用户的角色
	 * 权限:用户为1:N关系，得到用户对象的角色。
	 * @return
	 */
	public Role getRole(){
		return Role.dao.findById(get("roleId"));
	}
}
